import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Paths from "@/components/paths";
import { readFilesFromDir } from "@/util/get_folders";
import styles from '@/app/page.module.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const files = (await readFilesFromDir(`./src/app`))
  return (
    <html lang="is">
      <body className={inter.className}>
      <header>
		<Paths files={files} image="" />
	  </header>
		<main className={styles.main}>{children}</main>
        </body>
    </html>
  );
}