import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Paths from "@/components/Paths";
import { readFilesFromDir } from "@/util/get_folders";
import styles from '@/app/layout.module.scss'
import { Logout } from "@/components/Logout";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const files = (await readFilesFromDir(`./src/app`))
	return (
		<html lang="is">
			<body className={inter.className}>
				<header>
					<Paths files={files} image="" />
				</header>
				<main className={styles.main}>{children}</main>
				<footer className={styles.footer}>
					<Logout />
					<p>Elli og Addi production</p>
					<Link href={'/Notandi/Admin'}>Admin</Link>
				</footer>
			</body>
		</html>
	);
}